const ACTION_PREPEND = 'twitch-digits/snapshots/';

const SNAPSHOT_REQUEST = ACTION_PREPEND + 'SNAPSHOT_REQUEST';
const SNAPSHOT_RECEIVE = ACTION_PREPEND + 'SNAPSHOT_RECEIVE';

export default {
    SNAPSHOT_REQUEST,
    SNAPSHOT_RECEIVE
};