const ACTION_PREPEND = 'twitch-digits/snapshots/';

const SUMMARIES_REQUEST = ACTION_PREPEND + 'SUMMARIES_REQUEST';
const SUMMARIES_RECEIVE = ACTION_PREPEND + 'SUMMARIES_RECEIVE';

const SUMMARY_ADD = ACTION_PREPEND + 'SUMMARY_ADD';

export default {
    SUMMARIES_REQUEST,
    SUMMARIES_RECEIVE,
    SUMMARY_ADD
};