const ACTION_PREPEND = 'twitch-digits/snapshots/';

export const SUMMARIES_REQUEST = ACTION_PREPEND + 'SUMMARIES_REQUEST';
export const SUMMARIES_RECEIVE = ACTION_PREPEND + 'SUMMARIES_RECEIVE';

export const SUMMARY_ADD = ACTION_PREPEND + 'SUMMARY_ADD';
